### ISSUE TITLE
Server crash when trying to replace sandstone slab

### ISSUE THREAD

**Issue by MrAkells** [LemADEC/UndergroundBiomesConstructs#2]
I get a crash when moving around the world. I also attach the full log to the link.
https://mclo.gs/Vsa9Oyr

```
java.lang.NullPointerException
    at exterminatorjeff.undergroundbiomes.world.UBStoneReplacer.replaceStoneInChunk(UBStoneReplacer.java:189)
    at exterminatorjeff.undergroundbiomes.world.WorldGenManager.doProcess(WorldGenManager.java:98)
    at exterminatorjeff.undergroundbiomes.world.WorldGenManager.onProcess(WorldGenManager.java:89)
    at exterminatorjeff.undergroundbiomes.world.WorldGenManager.onPopulateChunkPost(WorldGenManager.java:77)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3255_WorldGenManager_onPopulateChunkPost_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.onChunkPopulate(ForgeEventFactory.java:769)
    at rtg.world.gen.ChunkGeneratorRTG.func_185931_b(ChunkGeneratorRTG.java:388)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(PlayerChunkMap.java:226)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by Niduin** [comment]
I got the same issue:

https://mclo.gs/6NXoj08
